### ISSUE TITLE
Add support for partial page replacement strategies with Turbograft

### ISSUE THREAD

**Issue by hason** [helthe/Turbolinks#4] opened 2015-02-06 22:16 UTC
https://github.com/Shopify/turbograft

**Comment by carlalexander** [comment] 2015-02-18 14:59
I'm waiting to see how they integrate various turbograft functionalities into the library first. Right now Turbolinks has a [ticket](https://github.com/rails/turbolinks/issues/448) for partial page replacement in the works.

**Comment by carlalexander** [comment] 2015-02-18 15:05
Took a bit more of a look at the turbograft library as well. The ruby code looks the same except for `xhr_headers.rb` which add a few changes done. That said, the changes done seem to mirror the changes I did before the last version.

This means that you should be able to replace the `turbolinks.js` with a compiled version of `turbograft.coffee`.

**Comment by carlalexander** [comment] 2015-03-06 21:00
So the issue is closed and there's a [merged PR](https://github.com/rails/turbolinks/issues/468) for the partial page replacement. It'll be in the moment they do a new release.

**Closed by carlalexander** 2015-03-06 21:00 UTC
